name: bear blog client

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Cache
      uses: actions/cache@v3.3.2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}          
        
    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn install
      
    - name: Build
      run: yarn build

    - name: Copy Deploy Resource
      run: |
        mkdir dist
        cp -r ./bin ./dist
        cp -r ./prisma ./dist
        cp ./appspec.yml ./dist
        cp ./package.json ./dist
        cp -r ./.github/deploy-script ./dist

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        name: bear-blog-server-prod
        path: ./dist/          
      
  deploy:
    env:
      ENV_PATH: .env
      S3_BUCKET_DIR_NAME: server/production
      DEPLOYMENT_GROUP_NAME: production
    needs: build
    runs-on: ubuntu-latest 
    
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.2
      with:
        name: bear-blog-server-prod

    - name: set env
      working-directory: ./
      run: |
        pwd
        touch .env
        echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
        cat .env

    - name: 📦 Zip project files
      run: zip -r ./$GITHUB_SHA.zip .
  
    - name: 🚛 Beanstalk Deploy
      uses: einaregilsson/beanstalk-deploy@v21
      with:        
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: ap-northeast-2
        application_name: bear-blog
        environment_name: Bear-blog-env
        version_label: ${{ github.run_number }}
        use_existing_version_if_available: true
    
